"""empty message

Revision ID: 388434399795
Revises: b2b3d5bab179
Create Date: 2025-01-21 11:35:16.695838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '388434399795'
down_revision = 'b2b3d5bab179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('banner_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('banner_url')
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
