"""Check for schema changes

Revision ID: 56063d671bce
Revises: be77a300309b
Create Date: 2025-04-04 21:53:35.285329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56063d671bce'
down_revision = 'be77a300309b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('social1', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('social2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('social3', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('social4', sa.String(), nullable=True))
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('social4')
        batch_op.drop_column('social3')
        batch_op.drop_column('social2')
        batch_op.drop_column('social1')

    # ### end Alembic commands ###
