"""Added artwork_url to MediaFile model

Revision ID: 63eff5990d0c
Revises: 83eaa9ef0dae
Create Date: 2025-03-08 04:19:58.781043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63eff5990d0c'
down_revision = '83eaa9ef0dae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artwork_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.drop_column('artwork_url')

    # ### end Alembic commands ###
