"""Add new contact fields from ERD

Revision ID: 83eaa9ef0dae
Revises: e158c1a0f465
Create Date: 2025-02-20 18:51:59.237016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83eaa9ef0dae'
down_revision = 'e158c1a0f465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('picture_icon', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('logo', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('logo')
        batch_op.drop_column('picture_icon')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
