"""Add Projects and ProjectMedia tables

Revision ID: be77a300309b
Revises: 63eff5990d0c
Create Date: 2025-03-17 21:05:12.671050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be77a300309b'
down_revision = '63eff5990d0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_pic', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_projects_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('media_file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.id'], name=op.f('fk_project_media_media_file_id_media_files')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_media_project_id_projects')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_media')
    op.drop_table('projects')
    # ### end Alembic commands ###
